### ISSUE TITLE
Add database relations/functionality for subscription to the blog

### ISSUE THREAD

**Issue by steverusso** [steverusso/cwhatsgood#26]
##### 1. Email table
There needs to be a table created in the DB that will hold email addresses for when people subscribe to the blog.
##### 2. Subscribe/Unsubscribe functions
There needs to be stored functions that will be used to subscribe and unsubscribe users.

Additions should be made on the 'createBlogSection' branch or any branch off of that.

**Comment by russoj88** [comment]
@steverusso is this just for subscription or can people login/out?  Can a user have multiple email addresses?
I think we should store a timestamp of when they first subscribed.  We should probably store a log of when a user subscribes and unsubscribes as well.
I think we should plan for some kind of subscription levels and/or subscription types by giving each email an ID.

Can you define the unsubscribe feature?  Does a user click a link in the email with a random id?

**Comment by steverusso** [comment]
All really good points that I should have initially specified.

For now, no account system and no subscription levels. Just subscribing/unsubscribing.
(If the site grows a lot, then I like the idea of subscription levels.)
Having a log of when a user subscribes and unsubscribes I think is a really good idea.

For unsubscribing, I think that should be possible through a link in each email that will have an ID and the email address so that no one can unsubscribe someone else by either guessing the ID or entering their email address.
So storing an ID with each email address would make that system work.
